from typing import Protocol, Any

class Channel(Protocol):
    async def send(self, destination: str, content: str, **kwargs: Any) -> None: ...
    async def send_photo(self, destination: str, image_bytes: bytes, caption: str, **kwargs: Any) -> None: ...