version: '3.8'

networks:
  location_net:
    name: location_service_network

services:
  location-service:
    build: .
    container_name: location-service
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    networks:
      - location_net