version: '3.8'

services:
  location-service:
    build: .
    container_name: location-service
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp