FROM python:3.10-slim-bullseye

WORKDIR /app

RUN useradd --system --create-home appuser

ENV PYTHONPATH "${PYTHONPATH}:/app/src"

COPY pyproject.toml ./

COPY src ./src

RUN pip install --no-cache-dir .

RUN chown -R appuser:appuser /app

USER appuser

CMD ["location-service"]