FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONPATH "${PYTHONPATH}:/app/src"

COPY pyproject.toml ./
COPY src ./src

RUN pip install --no-cache-dir .

CMD ["backup-service"]