enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "204"
destination_language = "en"
ai_topic = "animation"

[feeds.general]
urls = [
  "https://www.animenewsnetwork.com/all/rss.xml",
  "https://www.crunchyroll.com/feed/news",
  "https://www.animationmagazine.net/feed/",
  "https://www.cartoonbrew.com/feed",
  "https://www.awn.com/news/rss.xml"
]
fetch_limit = 25
section_limit = 3
render_template = "🎨 Animation News\n\n{summary}"
generate_image = true

[feeds.anime_plus]
urls = [
  "https://myanimelist.net/rss/news.xml",
  "https://otakuusamagazine.com/feed/",
  "https://soranews24.com/feed/",
  "https://animecorner.me/feed/",
  "https://www.livechart.me/feeds/headlines",
  "https://comicbook.com/anime/feed/"
]
fetch_limit = 25
section_limit = 3
render_template = "🎌 Anime News\n\n{summary}"
generate_image = true

[feeds.industry_plus]
urls = [
  "https://www.animationmagazine.net/feed/",
  "https://www.cartoonbrew.com/feed",
  "https://www.awn.com/news/rss.xml",
  "https://www.indiewire.com/c/animation/feed/",
  "https://deadline.com/tag/animation/feed/",
  "https://blog.siggraph.org/feed/"
]
fetch_limit = 25
section_limit = 3
render_template = "💼 Animation Industry\n\n{summary}"
generate_image = true