enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "204"
destination_language = "en"
render_template = "🎨 Animation Digest ({section})\n\n{summary}"
generate_image = true

fetch_limit = 25
section_limit = 3
ai_topic = "animation"

[feeds]
general = [
  "https://www.animenewsnetwork.com/all/rss.xml",
  "https://www.crunchyroll.com/feed/news",
  "https://www.animationmagazine.net/feed/",
  "https://www.cartoonbrew.com/feed",
  "https://www.awn.com/news/rss.xml"
]
anime_plus = [
  "https://myanimelist.net/rss/news.xml",
  "https://otakuusamagazine.com/feed/",
  "https://soranews24.com/feed/",
  "https://animecorner.me/feed/",
  "https://www.livechart.me/feeds/headlines",
  "https://comicbook.com/anime/feed/"
]
industry_plus = [
  "https://www.animationmagazine.net/feed/",
  "https://www.cartoonbrew.com/feed",
  "https://www.awn.com/news/rss.xml",
  "https://www.indiewire.com/c/animation/feed/",
  "https://deadline.com/tag/animation/feed/",
  "https://blog.siggraph.org/feed/"
]