enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "204"
destination_language = "en"
render_template = "🎨 Animation Digest\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "animation"

[feeds]
general = [
  "https://www.animenewsnetwork.com/all/rss.xml",
  "https://www.crunchyroll.com/feed/news",
  "https://www.animationmagazine.net/feed/",
  "https://www.cartoonbrew.com/feed",
  "https://www.awn.com/news/rss.xml"
]