enabled = true
to = "telegram"
destination = "-1002918707721"

weather_json = "/run/monitors/weather/latest.json"
quakes_json  = "/run/monitors/earthquakes/last7d.json"

language = "ru"
include_quakes = true
