enabled = true
rpc_method = "logs.build"

to = "telegram"
destination_group = "-1002918707721"
destination_topic = "194"
destination_language = "en"

generate_image = false
render_template = "{summary}"

lookback_hours = 24

[components]

  [components.peripheral_scripts]
  log_dir = "/home/reekroo/peripheral_scripts/logs"
  error_patterns = ["failed", "error", "permission denied", "traceback"]

  [components.backup_service]
  log_dir = "/home/reekroo/backup_service/logs"
  error_patterns = ["failed", "error", "traceback", "unable to connect"]

  [components.location_service]
  log_dir = "/home/reekroo/location_service/logs"
  error_patterns = ["failed", "error", "exception"]

  [components.metrics_exporter]
  log_dir = "/home/reekroo/metrics_exporter/logs"
  error_patterns = ["failed", "error", "traceback"]

  [components.earthquake_monitor]
  log_dir = "/home/reekroo/earthquake_monitor/logs"
  error_patterns = ["failed", "timeout", "API error", "could not fetch"]
  
  [components.weather_monitor]
  log_dir = "/home/reekroo/weather_monitor/logs"
  error_patterns = ["failed", "timeout", "API error"]

  [components.ai_hub]
  log_dir = "/home/reekroo/ai_hub/logs"
  error_patterns = ["failed", "error", "traceback", "unable to connect", "timeout", "API error"]
