enabled = true
to = "telegram"
destination = "-1002918707721"
destination_language = "en"
render_template = "📊 Log Analytics Digest\n\n{summary}"
generate_image = false

lookback_hours = 24

[components]

  [components.backup_service]
  log_dir = "/home/reekroo/backup_service/logs"
  error_patterns = ["failed", "error", "traceback", "unable to connect"]

  [components.earthquake_monitor]
  log_dir = "/home/reekroo/earthquake_monitor/logs"
  error_patterns = ["failed", "timeout", "API error", "could not fetch"]

  [components.location_service]
  log_dir = "/home/reekroo/location_service/logs"
  error_patterns = ["failed", "error", "exception"]

  [components.metrics_exporter]
  log_dir = "/home/reekroo/metrics_exporter/logs"
  error_patterns = ["failed", "error", "traceback"]

  [components.weather_monitor]
  log_dir = "/home/reekroo/weather_monitor/logs"
  error_patterns = ["failed", "timeout", "API error"]

  [components.peripheral_scripts]
  log_dir = "/home/reekroo/peripheral_scripts/logs"
  error_patterns = ["failed", "error", "permission denied", "traceback"]