enabled = true
max_depth = 6

root = "/mnt/storage/media"
state_path = "state/media_index.json"
include_ext = [".mkv",".mp4",".avi",".mov"]

[recommender]
language = "ru"
genres   = ["sci-fi","action","horrors"]

[soon]
enabled = false
