enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "204"
destination_language = "en"
generate_image = false

max_depth = 6
root = "/mnt/storage/media"
state_path = "state/media_index.json"
include_ext = [".mkv",".mp4",".avi",".mov"]

[recommender]
language = "en"
genres   = ["sci-fi","action","horrors"]