enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "345"
destination_language = "en"
render_template = "🇺🇸 United States News Digest ({section})\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "news_us"

[feeds]
general = [
    "https://apnews.com/hub/us-news/rss",
    "https://feeds.reuters.com/Reuters/domesticNews",
    "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "https://feeds.npr.org/1001/rss.xml",
    "https://feeds.a.dj.com/rss/RSSWorldNews.xml"
]