enabled = true
rpc_method = "news.build"

to = "telegram"
destination_group = "-1002918707721"
destination_topic = "345"
destination_language = "en"

ai_topic = "news_us"

[feeds.general]
urls = [
  "https://apnews.com/hub/us-news/rss",
  "https://feeds.reuters.com/Reuters/domesticNews",
  "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
  "https://feeds.npr.org/1001/rss.xml",
  "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
  "https://www.usatoday.com/rss/news/",
  "https://www.latimes.com/world-nation/rss2.0.xml"
]
fetch_limit = 25
section_limit = 3
render_template = "🇺🇸 U.S. News\n\n{summary}"
generate_image = true

[feeds.politics]
urls = [
  "https://www.politico.com/rss/politics-news.xml",
  "https://thehill.com/feed/",
  "https://www.axios.com/feeds/feed.rss",
  "https://www.washingtonpost.com/politics/rss"
]
fetch_limit = 25
section_limit = 3
render_template = "🇺🇸 U.S. Politics\n\n{summary}"
generate_image = false

[feeds.economy]
urls = [
  "https://www.reuters.com/markets/us/rss",
  "https://www.wsj.com/xml/rss/3_7014.xml",
  "https://www.cnbc.com/id/10000664/device/rss/rss.html",
  "https://www.bloomberg.com/feeds/podcasts/etf-report.xml"
]
fetch_limit = 25
section_limit = 3
render_template = "🇺🇸 U.S. Economy\n\n{summary}"
generate_image = false