enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "214"
destination_language = "ru"
render_template = "🇹🇷 Turkish News Digest ({section})\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "news_tr"

[feeds]
general = [
  "https://www.trthaber.com/xml_mobile.php?cat=1",
  "https://www.aa.com.tr/tr/rss/default?cat=guncel",
  "https://feeds.bbci.co.uk/turkce/rss.xml",
  "https://www.cnnturk.com/feed/rss/all/news"
]
economy = [
  "https://www.ntv.com.tr/ekonomi.rss"
]