enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "220"
destination_language = "ru"
render_template = "🇷🇺 Russia News Digest ({section})\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "news_ru"

[feeds]
general = [
    "https://www.interfax.ru/rss.asp",
    "https://meduza.io/rss/news",
    "https://tass.ru/rss/v2.xml",
    "https://ria.ru/export/rss2/index.xml",
    "https://www.vedomosti.ru/rss/news"
]