enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "1209"
destination_language = "ru"
render_template = "🇵🇱 Poland News Digest ({section})\n\n{summary}"
generate_image = true

fetch_limit = 25
section_limit = 3
ai_topic = "news_pl"

[feeds]
general = [
  "https://www.tvn24.pl/najnowsze.xml",
  "https://pap-mediaroom.pl/rss",
  "https://www.rmf24.pl/rss",
  "https://rp.pl/rss_main",
  "https://www.polskieradio.pl/399/8214"
]
economy = [
  "https://www.bankier.pl/rss",
  "https://www.money.pl/rss/",
  "https://www.pb.pl/rss",
  "https://businessinsider.com.pl/.feed",
  "https://rp.pl/rss/541-biznes"
]
politics_world = [
  "https://www.tvp.info/informacje?xslt=tvp-info/news/rss.xslt",
  "https://wyborcza.pl/pub/rss/gazetawyborcza_kraj.xml",
  "https://notesfrompoland.com/feed/",
  "https://www.dw.com/pl/rss"
]
