enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "350"
destination_language = "ru"
render_template = "🇷🇺 Russia News Digest ({section})\n\n{summary}"
generate_image = true

fetch_limit = 25
section_limit = 3
ai_topic = "news_ru"

[feeds]
general = [
  "https://www.interfax.ru/rss.asp",
  "https://meduza.io/rss/news",
  "https://tass.ru/rss/v2.xml",
  "https://ria.ru/export/rss2/index.xml",
  "https://www.vedomosti.ru/rss/news",
  "https://www.rbc.ru/rss/news.rss",
  "https://www.kommersant.ru/RSS/news.xml"
]
intl_ru = [
  "https://www.bbc.com/russian/index.xml",
  "https://www.dw.com/ru/rss",
  "https://www.currenttime.tv/api/z$%24rss"
]
economy = [
  "https://www.rbc.ru/rss/economics.rss",
  "https://www.kommersant.ru/RSS/money.xml",
  "https://quote.rbc.ru/rss/all_news.xml"
]
