[daily_brief]
enabled = true
cron = "30 7 * * *"
rpc_method = "runner.execute_and_send"
params = { config_name = "daily" }

[dinner]
enabled = true
cron = [
  "15 12 * * *",
  "45 16 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "dinner" }

[media]
enabled = true
cron = "55 18 * * *"
rpc_method = "runner.execute_and_send"
params = { config_name = "media" }

[entertainment]
enabled = true
cron = "0 19 * * *"
rpc_method = "runner.execute_and_send"
params = { config_name = "entertainment" }

[gaming]
enabled = true
cron = [
  "40 7 * * *",
  "30 17 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "gaming" }

[news_main]
enabled = true
cron = [
  "45 7 * * *",
  "10 12 * * *",
  "10 18 * * *",
  "30 21 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news" }

[news_tr]
enabled = true
cron = [
  "00 8 * * *",
  "0 14 * * *",
  "0 22 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news_tr" }

[news_by]
enabled = true
cron = [
  "30 8 * * *",
  "0 13 * * *",
  "0 20 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news_by" }

[news_eu]
enabled = true
cron = [
  "15 8 * * *",
  "15 14 * * *",
  "15 20 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news_eu" }

[news_us]
enabled = true
cron = [
  "0 14 * * *",
  "30 20 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news_us" }

[news_ru]
enabled = true
cron = [
  "10 13 * * *",
  "25 20 * * *"
]
rpc_method = "runner.execute_and_send"
params = { config_name = "news_ru" }

[sys_digest]
enabled = true
cron = "0 9,15,21 * * *"
rpc_method = "runner.execute_and_send"
params = { config_name = "sys" }

[log_digest]
enabled = true
cron = "1 9,15,21 * * *"
rpc_method = "runner.execute_and_send"
params = { config_name = "logs" }