enabled = true
to = "telegram"
destination = "-1002918707721"
destination_topic = "1090"
destination_language = "ru"
render_template = "🔬 Science Digest\n\n{summary}"
generate_image = true

max_items = 25
ai_topic = "science"

[feeds]
general = [
  "http://rss.sciencedaily.com/all.xml",
  "https://www.sciencenews.org/feed",
  "https://phys.org/rss-feed/science-news/",
  "https://newscientist.com/feed/home/",
  "https://www.nature.com/nature.rss"
]