lookback = "24h"
min_priority = "warning"
max_restarts = 3
state_path = "state/sys_digest.json"

units = [
  "ai-hub-chat.service",
  "ai-hub.service",
  "location-monitor.service",
  "earthquake-monitor.service",
  "weather-monitor.service",
  "metrics-exporter.service",
  "backup.service",
  "bluetooth-manager.service",
  "wifi-lan-manager.service",
  "nvme-powermode-manager.service",
  "sound-controller.service",
  "sound-boot.service",
  "sound-shutdown.service",
  "button-manager.service",
  "oled-status.service",
  "ups-service.service",
]

[patterns]
disk = ["I/O error","EXT4-fs error","nvme.*timeout"]
net  = ["link is down","No route to host","connection refused"]
app  = ["Traceback","Unhandled","DeviceNotFoundError"]
