enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "197"
destination_language = "ru"
generate_image = false

weather_json = "/run/monitors/weather/latest.json"
quakes_json  = "/run/monitors/earthquakes/last7d.json"

language = "ru"
include_quakes = true
