FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONPATH "${PYTHONPATH}:/app"

COPY pyproject.toml ./

COPY ai_assistent ./ai_assistent
COPY chat_bot ./chat_bot
COPY core ./core
COPY functions ./functions
COPY mcp ./mcp
COPY runner ./runner

RUN pip install --no-cache-dir .
