
networks:
  ai_hub_net:
    name: ai_hub_network
  
services:
  mcp:
    build: .
    container_name: ai-hub-mcp
    restart: unless-stopped
    env_file: .env.prod
    command: python -m mcp
    volumes:
      - ./configs/prod:/app/configs:ro
      - ./config:/config:ro 
      - ./state:/app/state
      - /tmp:/tmp
    networks:
      - ai_hub_net

  runner:
    build: .
    container_name: ai-hub-runner
    restart: unless-stopped
    env_file: .env.prod
    command: python -m runner
    volumes:
      - ./configs/prod:/app/configs:ro
      - ./config:/config:ro 
      - /tmp:/tmp
    networks:
      - ai_hub_net
    depends_on:
      - mcp

  chat:
    build: .
    container_name: ai-hub-chat
    restart: unless-stopped
    env_file: .env.prod
    command: python -m chat_bot
    volumes:
      - ./configs/prod:/app/configs:ro
      - ./config:/config:ro 
      - ./state:/app/state
      - /tmp:/tmp
    networks:
      - ai_hub_net
    depends_on:
      - mcp