[project]
name = "ai-hub"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
  "google-generativeai>=0.7.2",
  "python-telegram-bot>=21.5",
  "APScheduler>=3.10",
  "pydantic>=2.7",
  "pydantic-settings>=2.4",
  "rich>=13.7",
  "feedparser>=6.0",
]

[tool.ruff]
line-length = 100
