server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: periphery scripts
    static_configs:
      - targets:
          - localhost
        labels:
          job: scripts
          host: raspberrypi
          __path__: /mnt/logs/scripts_logs/*.log

  - job_name: earthquake monitor app
    static_configs:
      - targets:
          - localhost
        labels:
          job: earthquake_monitor
          host: raspberrypi
          __path__: /mnt/logs/earthquake_monitor_logs/*.log

  - job_name: location service
    static_configs:
      - targets:
          - localhost
        labels:
          job: location_service
          host: raspberrypi
          __path__: /mnt/logs/location_service_logs/*.log

  - job_name: backup service
    static_configs:
      - targets:
          - localhost
        labels:
          job: backup_serviсe
          host: raspberrypi
          __path__: /mnt/logs/backup_serviсe_logs/*.log

  - job_name: weather service
    static_configs:
      - targets:
          - localhost
        labels:
          job: weather_service
          host: raspberrypi
          __path__: /mnt/logs/weather_service_logs/*.log