server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: periphery scripts
    static_configs:
      - targets:
          - localhost
        labels:
          job: scripts
          host: raspberrypi
          __path__: /mnt/logs/scripts_logs/*.log

  - job_name: earthquake monitor app
    static_configs:
      - targets:
          - localhost
        labels:
          job: earthquake_monitor
          host: raspberrypi
          __path__: /mnt/logs/earthquake_monitor_logs/*.log