enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "1090"
destination_language = "ru"
ai_topic = "culture"

[feeds.general]
urls = [
  "https://www.theguardian.com/culture/rss",
  "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
  "https://www.newyorker.com/feed/culture",
  "https://www.theatlantic.com/feed/channel/culture/",
  "https://www.vox.com/rss/culture",
  "https://www.bbc.com/culture/feed.rss",
  "https://www.dw.com/arts/rss"
]
fetch_limit = 25
section_limit = 3
render_template = "🎭 Culture News\n\n{summary}"
generate_image = true
