enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "217"
destination_language = "ru"
ai_topic = "news_by"

[feeds.general]
urls = [
  "https://zerkalo.io/rss/s/main.rss",
  "https://mediazona.by/rss",
  "https://www.onliner.by/feed",
  "https://euroradio.fm/en/podcast-feeds/bynews",
  "https://nashaniva.com/?c=rss"
]
fetch_limit = 25
section_limit = 3
render_template = "🇧🇾 Belarus News\n\n{summary}"
generate_image = true
