enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "350"
destination_language = "ru"
ai_topic = "news_ru"

[feeds.general]
urls = [
  "https://www.interfax.ru/rss.asp",
  "https://meduza.io/rss/news",
  "https://tass.ru/rss/v2.xml",
  "https://ria.ru/export/rss2/index.xml",
  "https://www.vedomosti.ru/rss/news",
  "https://www.rbc.ru/rss/news.rss",
  "https://www.kommersant.ru/RSS/news.xml"
]
fetch_limit = 25
section_limit = 3
render_template = "🇷🇺 Russia News\n\n{summary}"
generate_image = true
