enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "345"
destination_language = "en"
ai_topic = "news_us"

[feeds.general]
urls = [
  "https://apnews.com/hub/us-news/rss",
  "https://feeds.reuters.com/Reuters/domesticNews",
  "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
  "https://feeds.npr.org/1001/rss.xml",
  "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
  "https://www.usatoday.com/rss/news/",
  "https://www.latimes.com/world-nation/rss2.0.xml"
]
fetch_limit = 25
section_limit = 3
render_template = "🇺🇸 U.S. News\n\n{summary}"
generate_image = true
