enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "340"
destination_language = "ru"
ai_topic = "news_eu"

[feeds.general]
urls = [
  "https://www.politico.eu/feed",
  "https://www.consilium.europa.eu/en/rss",
  "https://euobserver.com/rss",
  "https://www.euronews.com/rss",
  "https://apnews.com/hub/europe/rss",
  "https://www.europarl.europa.eu/news/en/rss",
  "https://www.euractiv.com/feed/"
]
fetch_limit = 25
section_limit = 3
render_template = "🇪🇺 European Union News\n\n{summary}"
generate_image = true
