enabled = true
to = "telegram"
destination_group = "-1002918707721" 
destination_topic = "774" 
destination_language = "ru"
ai_topic = "news_ua"

[feeds.general]
urls = [
  "https://www.pravda.com.ua/rss/",
  "https://rss.rbc.ua/ukr/newsline.rss",
  "https://www.unian.ua/rss_all.rss",
  "https://nv.ua/rss/all.xml",
  "https://hromadske.ua/rss",
  "https://suspilne.media/rss/all",
  "https://www.bbc.com/ukrainian/index.xml",
  "https://lb.ua/rss"
]
fetch_limit = 25
section_limit = 3
render_template = "🇺🇦 Ukraine News\n\n{summary}"
generate_image = true
