enabled = true
to = "telegram"
destination_group = "-1002918707721"
destination_topic = "1090"
destination_language = "ru"
ai_topic = "technology"

[feeds.general]
urls = [
  "https://www.theverge.com/rss/index.xml",
  "http://feeds.arstechnica.com/arstechnica/index",
  "https://techcrunch.com/feed/",
  "https://www.wired.com/feed/rss",
  "https://www.engadget.com/rss.xml",
  "https://venturebeat.com/feed/",
  "https://www.cnet.com/rss/news/"
]
fetch_limit = 30
section_limit = 3
render_template = "💻 General Tech News\n\n{summary}"
generate_image = true