UNIVERSAL_NEWS_DIGESTS = {
    "news", 
    "news_pl", 
    "news_by", 
    "news_ua",
    "news_ru",
    "news_tr", 
    "news_eu", 
    "news_us",  
    "news_fun",
    "gaming", 
    "animation",
    "entertainment",
    "culture",
    "science",
    "technology",
}

DIGEST_ALIASES = {
    "us": "news_us",
    "usa": "news_us",
    "america": "news_us",
    "eu": "news_eu",
    "europe": "news_eu",
    "pl": "news_pl",
    "poland": "news_pl",
    "ru": "news_ru",
    "russia": "news_ru",
    "by": "news_by",
    "belarus": "news_by",
    "ua": "news_ua",
    "ukraine": "news_ua",
    "tr": "news_tr",
    "turkey": "news_tr",
    "turkiye": "news_tr",
    "fun": "news_fun",
    "humor": "news_fun",
    "satire": "news_fun",
}