# config.yml

title: "My Media Server"
subtitle: "Dashboard"
icon: "fas fa-desktop"

header: true
footer: '<p>Created with ❤️ by Me</p>'

services:
  - name: "Media Management"
    icon: "fas fa-cogs"
    items:
      - name: "Sonarr"
        icon: "fas fa-video"
        subtitle: "TV Shows"
        tag: "app"
        url: "http://192.168.0.118:8989"
      - name: "Radarr"
        icon: "fas fa-film"
        subtitle: "Movies"
        tag: "app"
        url: "http://192.168.0.118:7878"
      - name: "Prowlarr"
        icon: "fas fa-search"
        subtitle: "Indexers"
        tag: "app"
        url: "http://192.168.0.118:9696"
      - name: "qBittorrent"
        icon: "fas fa-download"
        subtitle: "Downloads"
        tag: "app"
        url: "http://192.168.0.118:8080"

  - name: "Media Center"
    icon: "fas fa-film"
    items:
      - name: "Jellyfin"
        icon: "fas fa-server"
        subtitle: "Watch now"
        tag: "app"
        url: "http://192.168.0.118:8096"
      - name: "Jellyseerr"
        icon: "fas fa-ticket-alt"
        subtitle: "Requests"
        tag: "app"
        url: "http://192.168.0.118:5055"
      - name: "TorrServer"
        icon: "fas fa-bolt"
        subtitle: "Torrent Streaming"
        tag: "app"
        url: "http://192.168.0.118:8090"

  - name: "Utilities"
    icon: "fas fa-server"
    items:      
      - name: "Organizr"
        icon: "fas fa-sitemap"
        subtitle: "Unified Interface"
        tag: "infra"
        url: "http://192.168.0.118:9983/"
      - name: "Portainer"
        icon: "fab fa-docker"
        subtitle: "Container Management"
        tag: "infra"
        url: "https://192.168.0.118:9443"
      - name: "Nginx Proxy Manager"
        icon: "fas fa-network-wired"
        subtitle: "Proxy"
        tag: "infra"
        url: "http://192.168.0.118:81"
