version: "3.8"

networks:
  media-network:
    driver: bridge

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${STORAGE_PATH}/configs/qbittorrent:/config
      - ${STORAGE_PATH}/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - media-network
    logging: &logging_defaults
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 2m
      timeout: 10s
      retries: 3
    logging: *logging_defaults
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/radarr:/config
      - ${STORAGE_PATH}/media:/media
      - ${STORAGE_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7878/api/v3/system/status?apiKey=b9bca9398ee546a08e633fa170523be1"]
      interval: 2m
      timeout: 10s
      retries: 3
    logging: *logging_defaults
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/sonarr:/config
      - ${STORAGE_PATH}/media:/media
      - ${STORAGE_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8989/api/v3/system/status?apiKey=03fd017a7ed94c598d749b649039091f"]
      interval: 2m
      timeout: 10s
      retries: 3
    logging: *logging_defaults
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5055"]
      interval: 2m
      timeout: 10s
      retries: 3
    logging: *logging_defaults
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/jellyfin:/config
      - ${STORAGE_PATH}/caches/jellyfin-cache:/cache
      - ${STORAGE_PATH}/media/movies:/media/movies
      - ${STORAGE_PATH}/media/tvshowes:/media/tvshowes
      - ${STORAGE_PATH}/media/cartoons:/media/cartoons
      - ${STORAGE_PATH}/media/adultanimation:/media/adultanimation
      - ${STORAGE_PATH}/media/anime:/media/anime
      - ${STORAGE_PATH}/downloads:/media/new-items
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 2m
      timeout: 10s
      retries: 3
    logging: *logging_defaults
    restart: unless-stopped

  torrserver:
    image: yourok/torrserver:latest
    container_name: torrserver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/torrserver:/app/.config
      - ${STORAGE_PATH}/caches/torrserver-cache:/app/cache
      - ${STORAGE_PATH}/downloads:/app/downloads
    ports:
      - 8090:8090
    networks:
      - media-network
    logging: *logging_defaults
    restart: unless-stopped

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STORAGE_PATH}/configs/organizr:/config
    ports:
      - 9983:80
    networks:
      - media-network
    logging: *logging_defaults
    restart: unless-stopped
